services:
  db:
    ports:
      - "127.0.0.1:15432:5432"

  app:
    build:
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - dev_node_modules:/app/node_modules
      - dev_next:/app/.next

volumes:
  dev_node_modules:
  dev_next:
