import type { PublicSession } from "@/shared/contracts";

export const questions = [
  { id: "intent", eyebrow: "YOUR WORLD, YOUR WAY", title: "What brings you to ChaChat?", description: "There’s no right answer. Just what feels like you.", options: [["talk", "Someone to talk to", "A little company, whenever you need it", "✦"], ["story", "Interactive stories & role-play", "Step into a world of your own", "☾"], ["create", "Create a character", "Bring your imagination to life", "✎"], ["inspiration", "Creative inspiration", "Find your next spark", "☀"]] },
  { id: "character_type", eyebrow: "MEET YOUR MATCH", title: "Who would you like to meet first?", description: "Every great conversation starts with a connection.", options: [["friend", "A supportive friend", "Easy conversation. A familiar feeling.", "♡"], ["romantic", "A romantic companion", "A connection with a little chemistry", "❀"], ["fantasy", "A fantasy or story character", "Someone from another world", "☾"], ["surprise", "Surprise me", "Let curiosity lead the way", "✦"]] },
  { id: "interaction_mode", eyebrow: "FIND YOUR RHYTHM", title: "How do you want to connect?", description: "Make the conversation feel natural to you.", options: [["text", "Text conversations", "A thought, a message, a new direction", "≋"], ["voice", "Voice conversations", "Hear your character come to life", "♫"], ["images", "AI-generated images", "Give your imagination a visual world", "▧"], ["mix", "A mix of everything", "Explore all the possibilities", "✦"]] },
  { id: "memory", eyebrow: "MAKE IT PERSONAL", title: "What should your character remember?", description: "A little context can make your next chat feel more you.", options: [["interests", "My interests", "The things I love talking about", "♡"], ["story", "Our ongoing story", "Pick up where the adventure left off", "☾"], ["boundaries", "My preferences & boundaries", "The details that matter to me", "◇"], ["casual", "Let’s keep it casual", "A fresh conversation, any time", "☀"]] },
  { id: "usage_moment", eyebrow: "A MOMENT FOR YOU", title: "When would ChaChat fit into your day?", description: "Find a little space for a different kind of conversation.", options: [["daily", "A daily check-in", "A familiar hello in my routine", "☀"], ["unwind", "When I want to unwind", "Slow down and settle into a chat", "☾"], ["story", "Immersive story sessions", "Time to get lost in another world", "✦"], ["creative", "In my creative moments", "Follow an idea somewhere new", "✎"]] },
] as const;

export const APP_STORE_URL = "https://apps.apple.com/us/app/chachat-talking-ai-character/id6444773124";
export function matchSummary(answers: PublicSession["answers"]) {
  const character = { friend: "a supportive friend", romantic: "a romantic companion", fantasy: "a fantasy storyteller", surprise: "an unexpected new character" }[answers.character_type?.[0] ?? ""] ?? "a character that feels like you";
  const mode = { text: "thoughtful text conversations", voice: "expressive voice chats", images: "AI-generated imagery", mix: "text, voice, and visual possibilities" }[answers.interaction_mode?.[0] ?? ""] ?? "new conversations";
  return { title: answers.character_type?.[0] === "fantasy" ? "Your next chapter starts here." : "Your kind of connection awaits.", description: `Start with ${character} and explore ${mode}. Your answers are a starting point—you choose where the conversation goes.` };
}
